import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FaShieldAlt,
  FaCookieBite,
  FaUsers,
  FaLock,
  FaHandsHelping,
  FaEnvelope,
  FaArrowUp,
  FaDatabase,
  FaShareAlt,
  FaChild,
  FaLink,
  FaSyncAlt
} from "react-icons/fa";
import "./PrivacyPolicy.css";
import { Helmet } from 'react-helmet-async';

const PrivacyPolicy = () => {
    const [showBackToTop, setShowBackToTop] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            setShowBackToTop(window.scrollY > 400);
        };

        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const scrollToTop = () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };

    const sections = [
        {
            icon: <FaShieldAlt />,
            title: "Interpretation and Definitions",
            content: "",
            subsections: [
                {
                    subtitle: "Interpretation",
                    text: "The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
                },
                {
                    subtitle: "Definitions",
                    text: "For the purposes of this Privacy Policy:",
                    items: [
                        "Account means a unique account created for You to access our Service or parts of our Service.",
                        "Affiliate means an entity that controls, is controlled by, or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
                        "Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Privacy Policy) refers to QA Hub.",
                        "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
                        "Country refers to: Haryana, India",
                        "Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.",
                        "Personal Data (or 'Personal Information') is any information that relates to an identified or identifiable individual.",
                        "Service refers to the Website.",
                        "Service Provider means any natural or legal person who processes the data on behalf of the Company.",
                        "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
                        "Website refers to QA Hub, accessible from https://www.qahub.co.in/",
                        "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service."
                    ]
                }
            ]
        },
        {
            icon: <FaDatabase />,
            title: "Collecting and Using Your Personal Data",
            content: "",
            subsections: [
                {
                    subtitle: "Types of Data Collected",
                    text: "",
                    subsections: [
                        {
                            subtitle: "Personal Data",
                            text: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
                            items: ["Email address", "First name and last name", "Phone number", "Address, State, Province, ZIP/Postal code, City"]
                        },
                        {
                            subtitle: "Usage Data",
                            text: "Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."
                        },
                        {
                            subtitle: "Tracking Technologies and Cookies",
                            text: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.",
                            items: [
                                "Cookies or Browser Cookies: A cookie is a small file placed on Your Device.",
                                "Web Beacons: Certain sections of our Service and our emails may contain small electronic files known as web beacons.",
                                "Necessary / Essential Cookies: Session Cookies administered by Us for authentication and fraud prevention.",
                                "Cookies Policy / Notice Acceptance Cookies: Persistent Cookies administered by Us to identify if users have accepted cookies.",
                                "Functionality Cookies: Persistent Cookies administered by Us to remember choices You make."
                            ]
                        }
                    ]
                },
                {
                    subtitle: "Use of Your Personal Data",
                    text: "The Company may use Personal Data for the following purposes:",
                    items: [
                        "To provide and maintain our Service, including to monitor the usage of our Service.",
                        "To manage Your Account: to manage Your registration as a user of the Service.",
                        "For the performance of a contract: the development, compliance and undertaking of the purchase contract.",
                        "To contact You: by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
                        "To provide You with news, special offers, and general information about other goods, services and events.",
                        "To manage Your requests: To attend and manage Your requests to Us.",
                        "For business transfers: To evaluate or conduct a merger, divestiture, restructuring, or other sale or transfer of assets.",
                        "For other purposes: Such as data analysis, identifying usage trends, and evaluating our Service."
                    ]
                },
                {
                    subtitle: "Sharing Your Personal Data",
                    text: "We may share Your Personal Data in the following situations:",
                    items: [
                        "With Service Providers: To monitor and analyze the use of our Service.",
                        "For business transfers: In connection with any merger, sale of Company assets, financing, or acquisition.",
                        "With Affiliates: With Our parent company and any other subsidiaries or joint venture partners.",
                        "With business partners: To offer You certain products, services or promotions.",
                        "With other users: If Our Service offers public areas where You share Personal Data.",
                        "With Your consent: For any other purpose with Your consent."
                    ]
                }
            ]
        },
        {
            icon: <FaLock />,
            title: "Retention and Transfer of Your Personal Data",
            content: "",
            subsections: [
                {
                    subtitle: "Retention of Your Personal Data",
                    text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
                    items: [
                        "User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.",
                        "Customer Support Data: Support tickets and correspondence: up to 24 months from the date of ticket closure.",
                        "Usage Data: Website analytics data: up to 24 months from the date of collection.",
                        "Server logs: IP addresses, access times: up to 24 months for security monitoring."
                    ]
                },
                {
                    subtitle: "Transfer of Your Personal Data",
                    text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ."
                },
                {
                    subtitle: "Delete Your Personal Data",
                    text: "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account or by contacting Us."
                }
            ]
        },
        {
            icon: <FaShareAlt />,
            title: "Disclosure of Your Personal Data",
            content: "",
            subsections: [
                {
                    subtitle: "Business Transactions",
                    text: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy."
                },
                {
                    subtitle: "Law Enforcement",
                    text: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)."
                },
                {
                    subtitle: "Other Legal Requirements",
                    text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
                    items: [
                        "Comply with a legal obligation",
                        "Protect and defend the rights or property of the Company",
                        "Prevent or investigate possible wrongdoing in connection with the Service",
                        "Protect the personal safety of Users of the Service or the public",
                        "Protect against legal liability"
                    ]
                }
            ]
        },
        {
            icon: <FaCookieBite />,
            title: "Security, Cookies, and Children's Privacy",
            content: "",
            subsections: [
                {
                    subtitle: "Security of Your Personal Data",
                    text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security."
                },
                {
                    subtitle: "Children's Privacy",
                    text: "Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers."
                }
            ]
        },
        {
            icon: <FaLink />,
            title: "Links to Other Websites",
            content: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."
        },
        {
            icon: <FaSyncAlt />,
            title: "Changes to This Privacy Policy",
            content: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the 'Last updated' date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
        }
    ];

    return (
        <div className="privacy-policy-page">
            <Helmet>
                <title>Privacy Policy | QA Hub</title>
                <meta name="description" content="Read QA Hub's privacy policy to understand how we collect, use, and protect your personal information." />
                <meta property="og:title" content="Privacy Policy | QA Hub" />
                <meta property="og:url" content="https://www.qahub.co.in/privacy-policy" />
            </Helmet>
            {/* Header Section */}
            <motion.div
                className="privacy-header"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
            >
                <div className="header-content">
                    <motion.h1
                        initial={{ y: -30, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ duration: 0.8 }}
                    >
                        Privacy Policy
                    </motion.h1>
                    <motion.div
                        className="effective-date"
                        initial={{ y: 30, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ duration: 0.8, delay: 0.2 }}
                    >
                        Last updated: April 21, 2026
                    </motion.div>
                    <motion.p
                        className="policy-intro"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.8, delay: 0.3 }}
                    >
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </motion.p>
                </div>
            </motion.div>

            {/* Main Content */}
            <div className="privacy-container">
                <motion.div
                    className="policy-card"
                    initial={{ opacity: 0, y: 50 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.3 }}
                >
                    {/* Render all sections */}
                    {sections.map((section, sectionIndex) => (
                        <motion.div
                            key={sectionIndex}
                            className="policy-section"
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.5, delay: 0.4 + sectionIndex * 0.1 }}
                        >
                            <div className="section-header">
                                <div className="section-icon">
                                    {section.icon}
                                </div>
                                <h2>{section.title}</h2>
                            </div>

                            {/* Handle sections with subsections */}
                            {section.subsections ? (
                                section.subsections.map((sub, subIndex) => (
                                    <div key={subIndex} className="policy-subsection">
                                        {sub.subtitle && <h3>{sub.subtitle}</h3>}
                                        {sub.text && <p>{sub.text}</p>}
                                        {sub.items && (
                                            <ul className="policy-list">
                                                {sub.items.map((item, itemIndex) => (
                                                    <li key={itemIndex}>
                                                        <span className="list-bullet">•</span>
                                                        <span>{item}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                        )}
                                        {/* Handle nested subsections (like Personal Data under Types) */}
                                        {sub.subsections && sub.subsections.map((nested, nestedIndex) => (
                                            <div key={nestedIndex} className="policy-subsection">
                                                {nested.subtitle && <h4>{nested.subtitle}</h4>}
                                                {nested.text && <p>{nested.text}</p>}
                                                {nested.items && (
                                                    <ul className="policy-list">
                                                        {nested.items.map((item, itemIndex) => (
                                                            <li key={itemIndex}>
                                                                <span className="list-bullet">•</span>
                                                                <span>{item}</span>
                                                            </li>
                                                        ))}
                                                    </ul>
                                                )}
                                            </div>
                                        ))}
                                    </div>
                                ))
                            ) : (
                                <p>{section.content}</p>
                            )}
                        </motion.div>
                    ))}

                    {/* Contact Section */}
                    <motion.div
                        className="contact-section"
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ duration: 0.5, delay: 1.2 }}
                    >
                        <h2>Contact Us</h2>
                        <p>
                            If you have any questions about this Privacy Policy, You can contact us:
                        </p>
                        <motion.button
                            className="contact-btn"
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            onClick={() => window.location.href = "https://www.qahub.co.in/contact"}
                        >
                            <FaEnvelope /> Visit our Contact Page <FaArrowUp className="arrow-icon" />
                        </motion.button>
                    </motion.div>
                </motion.div>
            </div>

            {/* Back to Top Button */}
            <AnimatePresence>
                {showBackToTop && (
                    <motion.button
                        className="back-to-top"
                        onClick={scrollToTop}
                        initial={{ opacity: 0, scale: 0 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0 }}
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                    >
                        <FaArrowUp />
                    </motion.button>
                )}
            </AnimatePresence>
        </div>
    );
};

export default PrivacyPolicy;